apiVersion: v1
kind: Service
metadata:
  name: luolabot
  labels:
    app: luolabot
spec:
  ports:
  - port: 7175
    name: web
  clusterIP: None
  selector:
    app: luolabot
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: luolabot
  namespace: default
spec:
  serviceName: "luolabot"
  replicas: 2
  selector:
    matchLabels:
      app: luolabot
  template:
    metadata:
      labels:
        app: luolabot
    spec:
      containers:
      - name: luolabot
        image: python:latest
        command: ['sh', '-c', '/code/launch-luola-bot.sh']
        volumeMounts:
        - name: luola-bot-code
          mountPath: /code
        - name: luola-bot-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: luola-bot-code
        hostPath:
          path: {{pwd}}
      - name: luola-bot-config
        secret:
          secretName: luola-bot-config
          items:
          - key: "luolabot.yaml"
            path: "luolabot.yaml"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
