apiVersion: apps/v1
kind: Deployment
metadata:
  name: luolabot
  namespace: default
spec:
  serviceName: "luolabot"
  replicas: 1
  selector:
    matchLabels:
      app: luolabot
  template:
    metadata:
      labels:
        app: luolabot
    spec:
      containers:
      - name: luolabot
        image: ghcr.io/juuso22/luolabot-operator:0.0.1
        imagePullPolicy: Always
        env:
          - name: KUBECONFIG
            value: "/kubeconf.yaml"
        volumeMounts:
        - name: luola-bot-kube-config
          mountPath: /kubeconf.yaml
          readOnly: true
      volumes:
      - name: luola-bot-kube-config
        secret:
          secretName: luola-bot-kube-config
          items:
          - key: "kubeconf.yaml"
            path: "kubeconf.yaml"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
