apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: luolabots.luolabot.tg
spec:
  group: luolabot.tg
  names:
    plural: luolabots
    singular: luolabot
    kind: LuolaBot
    shortNames:
    - lb
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: ["botTokenSecret"]
            properties:
              botTokenSecret:
                type: string
              image:
                type: string
              disable_default_db_api:
                type: boolean
              db_apis:
                type: array
                items:
                  type: object
                  required: ["url"]
                  properties:
                    url:
                      type: string
                    username:
                      type: string
                    passwordSecret:
                      type: string
